name: Go
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.2'
    - name: Go to the root directory
      run: cd ${{ github.workspace }}
    - name: Test
      run: go test -v ./... -coverprofile=coverage.out
    - name: Convert coverage to Lcov
      run: |
        go install github.com/jandelgado/gcov2lcov@latest
        gcov2lcov -infile=coverage.out -outfile=coverage.lcov
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage.lcov
