    name: Test

    on: [push]

    jobs:
      test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Go
            uses: actions/setup-go@v2
            with:
              go-version: 1.17 # Set this to the version of Go you want to use
        
          - name: Install dependencies
            run: |
              go mod download
        
          - name: Run tests
            run: |
              go get github.com/mattn/goveralls
              $GOPATH/bin/goveralls -service=github -coverprofile=coverage.out
        
          - name: Upload coverage to Coveralls
            env:
              COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
            run: |
              $GOPATH/bin/goveralls -coverprofile=coverage.out -service=github