    name: Test

    on: [push]

    jobs:
      test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Go
            uses: actions/setup-go@v2
            with:
              go-version: 1.22.2 
          
          - name: Go to the root directory
            run: cd ${{ github.workspace }}
      
          - name: Install dependencies
            run: |
              go mod download
        
          - name: Test
            run: go test -v ./... -coverprofile=coverage.out
        
          - name: Coveralls
            uses: coverallsapp/github-action@v1.1.2
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
